// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9I5rONsXokDLJw24dM_5D9f-Rvmr-jo',
    appId: '1:372369190316:web:cd9a17397fdc1840319e09',
    messagingSenderId: '372369190316',
    projectId: 'matetec-92c63',
    authDomain: 'matetec-92c63.firebaseapp.com',
    storageBucket: 'matetec-92c63.firebasestorage.app',
    measurementId: 'G-7DS073099S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dRGI9U8lEQUeS9SQG9KDm-uHP44Vqh4',
    appId: '1:372369190316:android:f5f9e69c0f2b375e319e09',
    messagingSenderId: '372369190316',
    projectId: 'matetec-92c63',
    storageBucket: 'matetec-92c63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQcECess8c3ASAZqIQdubiwGW6fycTyPw',
    appId: '1:372369190316:ios:31c46cc6391fb4a8319e09',
    messagingSenderId: '372369190316',
    projectId: 'matetec-92c63',
    storageBucket: 'matetec-92c63.firebasestorage.app',
    iosBundleId: 'com.example.matetec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQcECess8c3ASAZqIQdubiwGW6fycTyPw',
    appId: '1:372369190316:ios:31c46cc6391fb4a8319e09',
    messagingSenderId: '372369190316',
    projectId: 'matetec-92c63',
    storageBucket: 'matetec-92c63.firebasestorage.app',
    iosBundleId: 'com.example.matetec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa9I5rONsXokDLJw24dM_5D9f-Rvmr-jo',
    appId: '1:372369190316:web:799d29e6ad3cd11c319e09',
    messagingSenderId: '372369190316',
    projectId: 'matetec-92c63',
    authDomain: 'matetec-92c63.firebaseapp.com',
    storageBucket: 'matetec-92c63.firebasestorage.app',
    measurementId: 'G-BH8GTWPF2T',
  );

}